repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: zitadel
    url: https://charts.zitadel.com
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: minio
    url: https://charts.min.io/

releases:
  - name: create-certs
    namespace: default
    chart: ./certs
  - name: ingress
    # namespace: default
    chart: ./ingress
  - name: db
    namespace: default
    chart: bitnami/postgresql
    version: 12.10.0
    wait: true
    values:
      - https://raw.githubusercontent.com/zitadel/zitadel-charts/main/examples/4-machine-user/postgres-values.yaml
  - name: my-zitadel
    namespace: default
    chart: zitadel/zitadel
    values:
      - https://raw.githubusercontent.com/zitadel/zitadel-charts/main/examples/4-machine-user/zitadel-values.yaml
      - zitadel-values.yaml
  - name: my-grafana
    namespace: monitoring
    chart: grafana/grafana
    values:
      - grafana-values.yaml
    version: 8.8.4
  - name: pulumi-kubernetes-operator
    namespace: pulumi-kubernetes-operator
    chart: oci://ghcr.io/pulumi/helm-charts/pulumi-kubernetes-operator
    createNamespace: true
    version: "2.0.0"
    # values:
    # - image:
    #     pullPolicy: Never
    #     # registry: ""
    #     repository: pulumi-kubernetes-operator
    #     tag: v2.0-mine.0

  - name: minio-pulumi-state
    namespace: minio
    chart: minio/minio
    values:
      - minio-values.yaml
