zitadel:
  configmapConfig:
    # http://my-zitadel.local.amazinglyabstract.it 
    ExternalDomain: my-zitadel.local.amazinglyabstract.it 
    ExternalSecure: true
    ExternalPort: 443
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
  hosts:
  - host: my-zitadel.local.amazinglyabstract.it
    paths:
    - path: /
      pathType: Prefix