zitadel:
  configmapConfig:
    # http://my-zitadel.local.amazinglyabstract.it 
    ExternalDomain: my-zitadel.local.amazinglyabstract.it 
    ExternalSecure: true
    ExternalPort: 443
ingress:
  enabled: true
  hosts:
  - host: my-zitadel.local.amazinglyabstract.it
    paths:
    - path: /
      pathType: Prefix
extraManifests:
- 
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: GRPC
    name: '{{ include "zitadel.fullname" . }}-grpc'
  spec:
    rules:
    - host: my-zitadel.local.amazinglyabstract.it
      http:
        paths:
        - backend:
            service:
              name: '{{ include "zitadel.fullname" . }}-grpc'
              port:
                number: 8081
          path: /zitadel
          pathType: Prefix
-
  apiVersion: v1
  kind: Service
  metadata:
    name: '{{ include "zitadel.fullname" . }}-grpc'
  spec:
    type: ClusterIP
    ports:
      - port: 8081
        targetPort: 8081
        protocol: TCP
        name: grpc-server
        appProtocol: 'kubernetes.io/h2c'
    selector:
      app.kubernetes.io/instance: my-zitadel
      app.kubernetes.io/name: zitadel
