apiVersion: v1
kind: ServiceAccount
metadata:
  name: zitadel-pulumi
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-source:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: zitadel-pulumi
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-access
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["configmaps","secrets"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-access-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-access
subjects:
- kind: ServiceAccount
  name: zitadel-pulumi
  namespace: default
---
apiVersion: pulumi.com/v1alpha1
kind: Stack
metadata:
  name: zitadel-pulumi
  namespace: default
spec:
  serviceAccountName: zitadel-pulumi
  projectRepo: "https://github.com/driv/zitadel-pulumi"
  branch: main
  shallow: true
  stack: dev
  backend: "s3://pulumi-state?endpoint=minio.local.amazinglyabstract.it&s3ForcePathStyle=true"
  refresh: true
  repoDir: "zitadel-pulumi/"
  destroyOnFinalize: true
  # gitAuth:
  #   accessToken:
  #     type: Secret
  #     secret:
  #       name: git-auth-secret
  #       key: accessToken
  workspaceTemplate:
    spec:
      podTemplate:
        spec:
          containers:
            - name: pulumi
              volumeMounts:
              - name: zitadel-admin-sa
                mountPath: /share/source/zitadel-pulumi/zitadel-admin-sa.json
                subPath: zitadel-admin-sa.json
              env:
                - name: USER
                  value: "pulumi"
                - name: AWS_REGION
                  value: "us-east-1"
                - name: AWS_ACCESS_KEY_ID
                  value: "rootuser"
                - name: AWS_SECRET_ACCESS_KEY
                  value: "rootpass123"
                - name: GOCACHE
                  value: /tmp/go-build-cache
                - name: PULUMI_CONFIG_PASSPHRASE
                  value: ""
          volumes:
          - name: zitadel-admin-sa
            secret:
              secretName: zitadel-admin-sa
              items:
              - key: zitadel-admin-sa.json
                path: zitadel-admin-sa.json